// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtkcrccbiuiccmswynhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10a2NyY2NiaXVpY2Ntc3d5bmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDc4MDcsImV4cCI6MjA1Mjc4MzgwN30.36RGABCvoK8I24LrKxGxwTdMmpAUiPZVEXBppUX4kh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);